#!/usr/bin/env node
/**
 * Regenerates src/core/catalog_fallback.js — the catalog the server falls back
 * to when it cannot read its own source off disk.
 *
 * Run this after adding or removing a tool, and after a version bump:
 *   node scripts/gen_tool_catalog.js
 *
 * tests/startup_resilience.test.js fails if the generated file drifts from the
 * live scan or from package.json, so the fallback cannot go stale unnoticed.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { discoverToolCatalogDetailed } from '../src/core/capabilities.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src', 'core', 'catalog_fallback.js');

const scan = discoverToolCatalogDetailed();
// Never write a fallback derived from the fallback: that would freeze whatever
// was already on disk and call it fresh.
if (scan.source !== 'scan') {
  console.error(`refusing to generate: the tool scan itself failed (${scan.error})`);
  process.exitCode = 1;
} else {
  const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
  const body = `// GENERATED by scripts/gen_tool_catalog.js — do not edit by hand.
//
// The last-resort catalog. src/core/capabilities.js scans src/tools/ to derive
// the real one; this is what it uses when that scan throws, which is what
// happens under C:\\Program Files\\ ACLs on Windows. A server that cannot read
// its own source still has to serve tools.
//
// tests/startup_resilience.test.js asserts this file matches the live scan and
// package.json, so it fails the build rather than going quietly stale.

export const FALLBACK_VERSION = '${version}';

export const FALLBACK_TOOL_CATALOG = Object.freeze([
${scan.tools.map((name) => `  '${name}',`).join('\n')}
]);
`;
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT}: ${scan.tools.length} tools, version ${version}`);
}
